server:
    port: 8082

spring:
    profiles:
        active: qa

management:
    endpoints:
        web:
            exposure:
                include: "*"
---

spring:
    profiles: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/dcbapp
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Daily Code Buffer! Config created in application.properties. Using application.yml.

---

spring:
    profiles: qa
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/dcbapp-qa
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Daily Code Buffer! Config created in application.properties. Using application.yml.

---

spring:
    profiles: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/dcbapp-prod
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Daily Code Buffer! Config created in application.properties. Using application.yml.